export type ModuleStatus = "complete" | "in-progress" | "available" | "locked";
export type StageId = "one" | "two" | "three" | "four" | "five" | "six";

export type FirstModule = {
  id: number;
  code: string;
  stage: StageId;
  title: string;
  category: "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W";
  time: string;
  difficulty: "Easy" | "Moderate" | "Deep";
  status: ModuleStatus;
  lastUpdated?: string;
  dueForReview?: boolean;
};

export const CATEGORY_META = {
  A: { label: "Self-Discovery & Values", color: "var(--neon-pink)" },
  B: { label: "Market & Role Research", color: "var(--sunshine-orange)" },
  C: { label: "Synthesis & Growth", color: "var(--citrus-lime)" },
  D: { label: "Style & Systems", color: "var(--fuchsia-blast)" },
  E: { label: "Personal Professional Identity", color: "var(--berry-burst)" },
  F: { label: "Personal Brand Foundations", color: "var(--juicy-plum)" },
  G: { label: "Digital Presence & Online Identity", color: "var(--tropical-mango)" },
  H: { label: "Professional Communication", color: "var(--pink-grapefruit)" },
  I: { label: "Professional Visibility", color: "var(--lime-zest)" },
  J: { label: "Professional Materials", color: "var(--citrus-lime)" },
  K: { label: "Application Systems & Materials", color: "var(--sunshine-orange)" },
  L: { label: "Interview Preparation", color: "var(--fuchsia-blast)" },
  M: { label: "Closing the Loop & Offers", color: "var(--lime-zest)" },
  N: { label: "Mindset, Productivity & Habits", color: "var(--pink-grapefruit)" },
  O: { label: "Extra Edge & Standout Factor", color: "var(--juicy-plum)" },
  P: { label: "Thinking, Reasoning & Mental Models", color: "var(--tropical-mango)" },
  Q: { label: "Thinking Frameworks", color: "var(--juicy-plum)" },
  R: { label: "Written Communication", color: "var(--neon-pink)" },
  S: { label: "Verbal & Presentation Skills", color: "var(--sunshine-orange)" },
  T: { label: "Listening, Reading & Comprehension", color: "var(--citrus-lime)" },
  U: { label: "Interpersonal & Networking Communication", color: "var(--fuchsia-blast)" },
  V: { label: "Feedback, Reflection & Self-Assessment", color: "var(--berry-burst)" },
  W: { label: "Communication Systems & Tools", color: "var(--juicy-plum)" },
} as const;

export const STAGES: { id: StageId; label: string; shortLabel: string; href: string }[] = [
  { id: "one", label: "Stage One · Self-Awareness & Career Clarity", shortLabel: "Stage One", href: "/dashboard/stage" },
  { id: "two", label: "Stage Two · Professional Identity & Personal Brand", shortLabel: "Stage Two", href: "/dashboard/stage/two" },
  { id: "three", label: "Stage Three · Job Application & Interview Skills", shortLabel: "Stage Three", href: "/dashboard/stage/three" },
  { id: "four", label: "Stage Four · Mindset, Productivity & Habits", shortLabel: "Stage Four", href: "/dashboard/stage/four" },
  { id: "five", label: "Stage Five · Thinking, Reasoning & Mental Models", shortLabel: "Stage Five", href: "/dashboard/stage/five" },
  { id: "six", label: "Stage Six · Communication: Speaking, Reading, Writing", shortLabel: "Stage Six", href: "/dashboard/stage/six" },
];

const STAGE_ONE_FIRSTS: FirstModule[] = [
  { id: 1, code: "01", stage: "one", title: "Core Values Audit", category: "A", time: "45 to 60 min", difficulty: "Moderate", status: "complete", lastUpdated: "3 months ago" },
  { id: 2, code: "02", stage: "one", title: "Career Vision", category: "A", time: "2 to 3 hrs", difficulty: "Moderate", status: "complete", lastUpdated: "14 months ago", dueForReview: true },
  { id: 3, code: "03", stage: "one", title: "Personal Purpose Awareness", category: "A", time: "45 to 60 min", difficulty: "Deep", status: "complete", lastUpdated: "3 months ago" },
  { id: 4, code: "04", stage: "one", title: "Personal Brand Narrative", category: "A", time: "45 to 60 min", difficulty: "Moderate", status: "in-progress", lastUpdated: "2 days ago" },
  { id: 5, code: "05", stage: "one", title: "Strength Inventory", category: "A", time: "1 to 2 hrs", difficulty: "Easy", status: "available" },
  { id: 6, code: "06", stage: "one", title: "Weakness Awareness", category: "A", time: "1 to 2 hrs", difficulty: "Moderate", status: "available" },
  { id: 7, code: "07", stage: "one", title: "Passion Alignment", category: "A", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 8, code: "08", stage: "one", title: "Industry Insight", category: "B", time: "2 to 4 hrs", difficulty: "Moderate", status: "locked" },
  { id: 9, code: "09", stage: "one", title: "Career Path", category: "B", time: "2 to 4 hrs", difficulty: "Moderate", status: "locked" },
  { id: 10, code: "10", stage: "one", title: "Role Research", category: "B", time: "4 to 8 hrs", difficulty: "Deep", status: "locked" },
  { id: 11, code: "11", stage: "one", title: "Salary Benchmarking", category: "B", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 12, code: "12", stage: "one", title: "Career SWOT Analysis", category: "C", time: "45 to 60 min", difficulty: "Moderate", status: "locked" },
  { id: 13, code: "13", stage: "one", title: "Skill Growth Plan", category: "C", time: "45 to 60 min", difficulty: "Moderate", status: "locked" },
  { id: 14, code: "14", stage: "one", title: "Personality Assessment", category: "D", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 15, code: "15", stage: "one", title: "Work Style Awareness", category: "D", time: "1 to 2 weeks", difficulty: "Moderate", status: "locked" },
  { id: 16, code: "16", stage: "one", title: "Thinking & Decision-Making Style", category: "D", time: "1 to 2 hrs", difficulty: "Deep", status: "locked" },
  { id: 17, code: "17", stage: "one", title: "Learning Style Awareness", category: "D", time: "3 days", difficulty: "Moderate", status: "locked" },
  { id: 18, code: "18", stage: "one", title: "Productivity & Focus System", category: "D", time: "1 week", difficulty: "Moderate", status: "locked" },
];

const STAGE_TWO_FIRSTS: FirstModule[] = [
  { id: 19, code: "B1", stage: "two", title: "Professional Introduction", category: "E", time: "1 to 1.5 hrs", difficulty: "Easy", status: "locked" },
  { id: 20, code: "B2", stage: "two", title: "Elevator Pitch", category: "E", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 21, code: "B3", stage: "two", title: "Personal Brand Statement", category: "E", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 22, code: "B4", stage: "two", title: "Professional Communication Style", category: "E", time: "3 to 4 wks", difficulty: "Moderate", status: "locked" },
  { id: 23, code: "B5", stage: "two", title: "Professional Confidence Mindset", category: "E", time: "1 semester", difficulty: "Moderate", status: "locked" },
  { id: 24, code: "B6", stage: "two", title: "Personal Value Statement", category: "E", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 25, code: "B7", stage: "two", title: "Personal Brand Strategy", category: "F", time: "2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 26, code: "B8", stage: "two", title: "Personal Brand Positioning", category: "F", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 27, code: "B9", stage: "two", title: "Professional Reputation Awareness", category: "F", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 28, code: "B10", stage: "two", title: "Professional Image Audit", category: "F", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 29, code: "B11", stage: "two", title: "Credibility Signals", category: "F", time: "4 to 8 wks", difficulty: "Moderate", status: "locked" },
  { id: 30, code: "B12", stage: "two", title: "Professional Boundaries", category: "F", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 31, code: "B13", stage: "two", title: "LinkedIn Profile", category: "G", time: "3 to 4 hrs", difficulty: "Easy", status: "locked" },
  { id: 32, code: "B14", stage: "two", title: "LinkedIn Headline Strategy", category: "G", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 33, code: "B15", stage: "two", title: "Professional Bio", category: "G", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 34, code: "B16", stage: "two", title: "Digital Footprint Audit", category: "G", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 35, code: "B17", stage: "two", title: "Personal Website", category: "G", time: "4 to 6 hrs", difficulty: "Moderate", status: "locked" },
  { id: 36, code: "B18", stage: "two", title: "Professional Portfolio", category: "G", time: "6 to 10 hrs", difficulty: "Deep", status: "locked" },
  { id: 37, code: "B19", stage: "two", title: "Professional Headshot", category: "G", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 38, code: "B20", stage: "two", title: "Branding Color Scheme & Logo", category: "G", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 39, code: "B21", stage: "two", title: "Professional Email Style", category: "H", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 40, code: "B22", stage: "two", title: "Professional Email Template", category: "H", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 41, code: "B23", stage: "two", title: "Meeting Presence", category: "H", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 42, code: "B24", stage: "two", title: "Question-Asking Skill", category: "H", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 43, code: "B25", stage: "two", title: "Professional Listening Skill", category: "H", time: "Several wks", difficulty: "Moderate", status: "locked" },
  { id: 44, code: "B26", stage: "two", title: "Public Speaking Recording", category: "H", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 45, code: "B27", stage: "two", title: "Video Introduction", category: "H", time: "1 to 2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 46, code: "B28", stage: "two", title: "Thoughtful Social Media Presence", category: "I", time: "1 hr setup", difficulty: "Moderate", status: "locked" },
  { id: 47, code: "B29", stage: "two", title: "LinkedIn Post Engagement", category: "I", time: "15 min/wk", difficulty: "Easy", status: "locked" },
  { id: 48, code: "B30", stage: "two", title: "Professional Content Share", category: "I", time: "15 to 20 min", difficulty: "Easy", status: "locked" },
  { id: 49, code: "B31", stage: "two", title: "Blog/Article Post", category: "I", time: "3 to 5 hrs", difficulty: "Deep", status: "locked" },
  { id: 50, code: "B32", stage: "two", title: "Thought Leadership Series", category: "I", time: "3 to 5 hrs", difficulty: "Deep", status: "locked" },
  { id: 51, code: "B33", stage: "two", title: "Industry Trend Report", category: "I", time: "3 to 4 hrs", difficulty: "Deep", status: "locked" },
  { id: 52, code: "B34", stage: "two", title: "Professional Conversation Starter", category: "I", time: "30 to 60 min", difficulty: "Easy", status: "locked" },
  { id: 53, code: "B35", stage: "two", title: "Resume That Stands Out", category: "J", time: "3 to 4 hrs", difficulty: "Moderate", status: "locked" },
  { id: 54, code: "B36", stage: "two", title: "Cover Letter That Works", category: "J", time: "1 to 2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 55, code: "B37", stage: "two", title: "Business Card / Email Signature", category: "J", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 56, code: "B38", stage: "two", title: "Portfolio/Project Showcase", category: "J", time: "2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 57, code: "B39", stage: "two", title: "Online Portfolio Review", category: "J", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 58, code: "B40", stage: "two", title: "Digital Presence Plan", category: "J", time: "1 hr", difficulty: "Easy", status: "locked" },
];

const STAGE_THREE_FIRSTS: FirstModule[] = [
  { id: 59, code: "C1", stage: "three", title: "Job Application Tracker", category: "K", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 60, code: "C2", stage: "three", title: "Application Strategy", category: "K", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 61, code: "C3", stage: "three", title: "Resume Version A/B Test", category: "K", time: "Ongoing", difficulty: "Deep", status: "locked" },
  { id: 62, code: "C4", stage: "three", title: "Cover Letter Customization", category: "K", time: "15 to 20 min", difficulty: "Moderate", status: "locked" },
  { id: 63, code: "C5", stage: "three", title: "Job Listing Analysis", category: "K", time: "10 to 15 min", difficulty: "Easy", status: "locked" },
  { id: 64, code: "C6", stage: "three", title: "STAR Answer Prep", category: "L", time: "3 to 4 hrs", difficulty: "Moderate", status: "locked" },
  { id: 65, code: "C7", stage: "three", title: "Behavioral Interview Prep", category: "L", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 66, code: "C8", stage: "three", title: "Technical Interview Prep", category: "L", time: "3 to 4 wks", difficulty: "Deep", status: "locked" },
  { id: 67, code: "C9", stage: "three", title: "Case/Problem-Solving Prep", category: "L", time: "3 to 4 wks", difficulty: "Deep", status: "locked" },
  { id: 68, code: "C10", stage: "three", title: "Mock Interview", category: "L", time: "45 min to 1 hr", difficulty: "Moderate", status: "locked" },
  { id: 69, code: "C11", stage: "three", title: "Job Offer Negotiation Prep", category: "M", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 70, code: "C12", stage: "three", title: "Follow-Up Email After Interview", category: "M", time: "10 to 15 min", difficulty: "Easy", status: "locked" },
  { id: 71, code: "C13", stage: "three", title: "Test/Assessment Prep", category: "L", time: "3 to 5 hrs", difficulty: "Moderate", status: "locked" },
  { id: 72, code: "C14", stage: "three", title: "Mock Presentation", category: "L", time: "3 to 4 hrs", difficulty: "Moderate", status: "locked" },
  { id: 73, code: "C15", stage: "three", title: "Interview Mindset Routine", category: "L", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 74, code: "C16", stage: "three", title: "Thank-You Email Habit", category: "M", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 75, code: "C17", stage: "three", title: "Application Deadline Calendar", category: "K", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 76, code: "C18", stage: "three", title: "Career-Focused LinkedIn Application", category: "M", time: "30 min", difficulty: "Moderate", status: "locked" },
  { id: 77, code: "C19", stage: "three", title: "Job Research Sheet", category: "K", time: "45 min to 1 hr", difficulty: "Moderate", status: "locked" },
  { id: 78, code: "C20", stage: "three", title: "Offer Comparison Matrix", category: "M", time: "1 hr", difficulty: "Moderate", status: "locked" },
];

const STAGE_FOUR_FIRSTS: FirstModule[] = [
  { id: 79, code: "E1", stage: "four", title: "Confidence Routine", category: "N", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 80, code: "E2", stage: "four", title: "Morning Productivity Ritual", category: "N", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 81, code: "E3", stage: "four", title: "Reflection Journal", category: "N", time: "5 min", difficulty: "Easy", status: "locked" },
  { id: 82, code: "E4", stage: "four", title: "Resilience Drill", category: "N", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 83, code: "E5", stage: "four", title: "Time Management Matrix", category: "N", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 84, code: "E6", stage: "four", title: "Daily Learning Habit", category: "N", time: "30 to 60 min", difficulty: "Easy", status: "locked" },
  { id: 85, code: "E7", stage: "four", title: "Micro-Skill Challenge", category: "N", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 86, code: "E8", stage: "four", title: "Personal KPI Tracker", category: "N", time: "5 min", difficulty: "Easy", status: "locked" },
  { id: 87, code: "E9", stage: "four", title: "Focus Routine", category: "N", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 88, code: "E10", stage: "four", title: "Gratitude Habit", category: "N", time: "2 min", difficulty: "Easy", status: "locked" },
  { id: 89, code: "E11", stage: "four", title: "Stress Management Technique", category: "N", time: "10 to 20 min", difficulty: "Easy", status: "locked" },
  { id: 90, code: "E12", stage: "four", title: "Accountability Partner", category: "N", time: "5 to 15 min", difficulty: "Easy", status: "locked" },
  { id: 91, code: "E13", stage: "four", title: "Learning Log", category: "N", time: "2 to 5 min", difficulty: "Easy", status: "locked" },
  { id: 92, code: "E14", stage: "four", title: "Habit Stacking Routine", category: "N", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 93, code: "E15", stage: "four", title: "Self-Assessment Review", category: "N", time: "45 min to 1 hr", difficulty: "Moderate", status: "locked" },
  { id: 94, code: "E16", stage: "four", title: "Energy Audit", category: "N", time: "1 wk", difficulty: "Easy", status: "locked" },
  { id: 95, code: "E17", stage: "four", title: "Goal Visualization Exercise", category: "N", time: "5 min", difficulty: "Easy", status: "locked" },
  { id: 96, code: "E18", stage: "four", title: "Affirmation Practice", category: "N", time: "2 min", difficulty: "Easy", status: "locked" },
  { id: 97, code: "E19", stage: "four", title: "Networking/Skill Challenge", category: "N", time: "2 hrs", difficulty: "Easy", status: "locked" },
  { id: 98, code: "E20", stage: "four", title: "Productivity Tool Setup", category: "N", time: "2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 99, code: "F1", stage: "four", title: "Side Project", category: "O", time: "Several wks", difficulty: "Deep", status: "locked" },
  { id: 100, code: "F2", stage: "four", title: "Volunteer/Impact Experience", category: "O", time: "1 semester", difficulty: "Deep", status: "locked" },
  { id: 101, code: "F3", stage: "four", title: "Certification/Badge", category: "O", time: "10 to 20 hrs", difficulty: "Moderate", status: "locked" },
  { id: 102, code: "F4", stage: "four", title: "Strategic Goal Sheet", category: "O", time: "1 hr", difficulty: "Moderate", status: "locked" },
  { id: 103, code: "F5", stage: "four", title: "Thought Leadership Post", category: "O", time: "3 to 5 hrs", difficulty: "Deep", status: "locked" },
];

const STAGE_FIVE_FIRSTS: FirstModule[] = [
  { id: 104, code: "G1", stage: "five", title: "Mental Model Awareness", category: "P", time: "1 hr", difficulty: "Easy", status: "locked" },
  { id: 105, code: "G2", stage: "five", title: "Cause-and-Effect Mapping", category: "P", time: "20 to 30 min", difficulty: "Easy", status: "locked" },
  { id: 106, code: "G3", stage: "five", title: "Problem Breakdown Exercise", category: "P", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 107, code: "G4", stage: "five", title: "Decision Matrix", category: "P", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 108, code: "G5", stage: "five", title: "Root Cause Analysis", category: "P", time: "20 min", difficulty: "Moderate", status: "locked" },
  { id: 109, code: "G6", stage: "five", title: "Critical Thinking Drill", category: "P", time: "10 to 15 min", difficulty: "Easy", status: "locked" },
  { id: 110, code: "G7", stage: "five", title: "Hypothesis Testing", category: "P", time: "1 to 2 wks", difficulty: "Moderate", status: "locked" },
  { id: 111, code: "G8", stage: "five", title: "Scenario Planning", category: "P", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 112, code: "G9", stage: "five", title: "Cognitive Bias Audit", category: "P", time: "45 min", difficulty: "Moderate", status: "locked" },
  { id: 113, code: "G10", stage: "five", title: "Systems Thinking Exercise", category: "P", time: "45 min to 1 hr", difficulty: "Moderate", status: "locked" },
  { id: 114, code: "G11", stage: "five", title: "Feedback Integration", category: "P", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 115, code: "G12", stage: "five", title: "Strategic Prioritization", category: "P", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 116, code: "G13", stage: "five", title: "Mental Model Application", category: "P", time: "30 min", difficulty: "Moderate", status: "locked" },
  { id: 117, code: "G14", stage: "five", title: "Pattern Recognition Drill", category: "P", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 118, code: "G15", stage: "five", title: "Reflection on Decision-Making", category: "P", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 119, code: "H16", stage: "five", title: "SWOT Thinking Exercise", category: "Q", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 120, code: "H17", stage: "five", title: "First-Principles Analysis", category: "Q", time: "45 min to 1 hr", difficulty: "Deep", status: "locked" },
  { id: 121, code: "H18", stage: "five", title: "Inversion Thinking Drill", category: "Q", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 122, code: "H19", stage: "five", title: "Opportunity Cost Exercise", category: "Q", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 123, code: "H20", stage: "five", title: "80/20 Analysis", category: "Q", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 124, code: "H21", stage: "five", title: "Systems Thinking Application", category: "Q", time: "1 hr", difficulty: "Deep", status: "locked" },
  { id: 125, code: "H22", stage: "five", title: "Decision Tree Exercise", category: "Q", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 126, code: "H23", stage: "five", title: "Scenario Analysis", category: "Q", time: "1 to 2 hrs", difficulty: "Deep", status: "locked" },
  { id: 127, code: "H24", stage: "five", title: "Checklists & SOPs Creation", category: "Q", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 128, code: "H25", stage: "five", title: "Root Cause Framework", category: "Q", time: "20 min", difficulty: "Moderate", status: "locked" },
  { id: 129, code: "H26", stage: "five", title: "Feedback Loop Exercise", category: "Q", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 130, code: "H27", stage: "five", title: "Comparative Analysis", category: "Q", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 131, code: "H28", stage: "five", title: "Mental Model Combination", category: "Q", time: "45 min to 1 hr", difficulty: "Deep", status: "locked" },
  { id: 132, code: "H29", stage: "five", title: "Hypothesis-Driven Approach", category: "Q", time: "Days to wks", difficulty: "Moderate", status: "locked" },
  { id: 133, code: "H30", stage: "five", title: "Strategic Mapping", category: "Q", time: "1 hr", difficulty: "Moderate", status: "locked" },
];

const STAGE_SIX_FIRSTS: FirstModule[] = [
  { id: 134, code: "I1", stage: "six", title: "Professional Email Sent", category: "R", time: "15 to 20 min", difficulty: "Easy", status: "locked" },
  { id: 135, code: "I2", stage: "six", title: "Meeting Agenda Prepared", category: "R", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 136, code: "I8", stage: "six", title: "Written Report Drafted", category: "R", time: "Several hrs", difficulty: "Moderate", status: "locked" },
  { id: 137, code: "I9", stage: "six", title: "Report Edited for Clarity", category: "R", time: "30 to 45 min", difficulty: "Easy", status: "locked" },
  { id: 138, code: "I10", stage: "six", title: "Technical Document Created", category: "R", time: "1 to 2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 139, code: "I15", stage: "six", title: "Persuasive Email Sent", category: "R", time: "20 to 30 min", difficulty: "Easy", status: "locked" },
  { id: 140, code: "I18", stage: "six", title: "Business Proposal Drafted", category: "R", time: "1 to 2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 141, code: "I19", stage: "six", title: "Meeting Minutes Documented", category: "R", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 142, code: "I24", stage: "six", title: "Summary Email Sent After Meeting", category: "R", time: "5 to 10 min", difficulty: "Easy", status: "locked" },
  { id: 143, code: "I33", stage: "six", title: "Follow-Up Email After Networking", category: "R", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 144, code: "I38", stage: "six", title: "Written Technical Summary", category: "R", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 145, code: "I39", stage: "six", title: "Email Etiquette Audit", category: "R", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 146, code: "I44", stage: "six", title: "Written Proposal Feedback", category: "R", time: "30 min + revision", difficulty: "Moderate", status: "locked" },
  { id: 147, code: "I46", stage: "six", title: "Email to Recruiter", category: "R", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 148, code: "I50", stage: "six", title: "Collaborative Document Editing", category: "R", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 149, code: "I62", stage: "six", title: "Written Executive Summary", category: "R", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 150, code: "I65", stage: "six", title: "Email Draft Templates Library", category: "R", time: "1 to 2 hrs", difficulty: "Easy", status: "locked" },
  { id: 151, code: "I3", stage: "six", title: "Presentation Script Written", category: "S", time: "30 to 45 min", difficulty: "Easy", status: "locked" },
  { id: 152, code: "I4", stage: "six", title: "Presentation Delivered", category: "S", time: "30 min", difficulty: "Moderate", status: "locked" },
  { id: 153, code: "I5", stage: "six", title: "Public Speaking Recording", category: "S", time: "45 min", difficulty: "Easy", status: "locked" },
  { id: 154, code: "I11", stage: "six", title: "Elevator Pitch Practiced", category: "S", time: "5 min/day, 1 wk", difficulty: "Easy", status: "locked" },
  { id: 155, code: "I20", stage: "six", title: "Storytelling Exercise", category: "S", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 156, code: "I21", stage: "six", title: "Voice Recording Review", category: "S", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 157, code: "I22", stage: "six", title: "Presentation Slide Deck Created", category: "S", time: "1 to 2 hrs", difficulty: "Moderate", status: "locked" },
  { id: 158, code: "I23", stage: "six", title: "Debate Participation", category: "S", time: "1 hr prep + debate", difficulty: "Moderate", status: "locked" },
  { id: 159, code: "I28", stage: "six", title: "Group Presentation Coordinated", category: "S", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 160, code: "I29", stage: "six", title: "Impromptu Speaking Drill", category: "S", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 161, code: "I31", stage: "six", title: "Persuasive Presentation", category: "S", time: "Several hrs", difficulty: "Deep", status: "locked" },
  { id: 162, code: "I51", stage: "six", title: "Presentation to Non-Expert Audience", category: "S", time: "45 min", difficulty: "Moderate", status: "locked" },
  { id: 163, code: "I57", stage: "six", title: "Elevator Pitch Refinement", category: "S", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 164, code: "I63", stage: "six", title: "Peer Learning Circle Presentation", category: "S", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 165, code: "I66", stage: "six", title: "Read-Aloud Exercise", category: "S", time: "5 min", difficulty: "Easy", status: "locked" },
  { id: 166, code: "I6", stage: "six", title: "Active Listening Drill", category: "T", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 167, code: "I14", stage: "six", title: "Reading Summary Exercise", category: "T", time: "15 to 20 min", difficulty: "Easy", status: "locked" },
  { id: 168, code: "I26", stage: "six", title: "Podcast or Video Commentary", category: "T", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 169, code: "I27", stage: "six", title: "Reading Comprehension Challenge", category: "T", time: "30 to 60 min", difficulty: "Moderate", status: "locked" },
  { id: 170, code: "I35", stage: "six", title: "Reading List for Career Growth", category: "T", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 171, code: "I47", stage: "six", title: "Reflective Reading Journal", category: "T", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 172, code: "I49", stage: "six", title: "Reading Speed & Comprehension Drill", category: "T", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 173, code: "I55", stage: "six", title: "Listening and Summarization Exercise", category: "T", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 174, code: "I12", stage: "six", title: "Networking Conversation", category: "U", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 175, code: "I13", stage: "six", title: "Mock Interview", category: "U", time: "45 min to 1 hr", difficulty: "Moderate", status: "locked" },
  { id: 176, code: "I16", stage: "six", title: "Discussion Facilitation", category: "U", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 177, code: "I17", stage: "six", title: "Cross-Cultural Communication Exercise", category: "U", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 178, code: "I32", stage: "six", title: "Professional Networking Introduction", category: "U", time: "15 min", difficulty: "Easy", status: "locked" },
  { id: 179, code: "I37", stage: "six", title: "Online Discussion Participation", category: "U", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 180, code: "I41", stage: "six", title: "Professional Chat with Senior", category: "U", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 181, code: "I42", stage: "six", title: "Conflict Resolution Conversation", category: "U", time: "15 to 30 min", difficulty: "Deep", status: "locked" },
  { id: 182, code: "I45", stage: "six", title: "Meeting Facilitation in Class/Group", category: "U", time: "Ongoing", difficulty: "Moderate", status: "locked" },
  { id: 183, code: "I48", stage: "six", title: "Online Course Discussion Participation", category: "U", time: "10 min", difficulty: "Easy", status: "locked" },
  { id: 184, code: "I53", stage: "six", title: "Professional Social Media Commenting", category: "U", time: "15 min/wk", difficulty: "Easy", status: "locked" },
  { id: 185, code: "I64", stage: "six", title: "Scenario-Based Communication Drill", category: "U", time: "20 to 30 min", difficulty: "Moderate", status: "locked" },
  { id: 186, code: "I69", stage: "six", title: "Public Forum Participation", category: "U", time: "Opportunity-dependent", difficulty: "Easy", status: "locked" },
  { id: 187, code: "I7", stage: "six", title: "Feedback Response", category: "V", time: "Ongoing", difficulty: "Easy", status: "locked" },
  { id: 188, code: "I25", stage: "six", title: "Professional Feedback Given", category: "V", time: "10 to 15 min", difficulty: "Easy", status: "locked" },
  { id: 189, code: "I30", stage: "six", title: "Written Reflection on Learning", category: "V", time: "15 to 20 min", difficulty: "Easy", status: "locked" },
  { id: 190, code: "I36", stage: "six", title: "Communication Self-Assessment", category: "V", time: "30 min", difficulty: "Easy", status: "locked" },
  { id: 191, code: "I40", stage: "six", title: "Reflection on Public Speaking Anxiety", category: "V", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 192, code: "I54", stage: "six", title: "Peer Review Feedback", category: "V", time: "20 to 30 min", difficulty: "Moderate", status: "locked" },
  { id: 193, code: "I60", stage: "six", title: "Reflective Speaking Log", category: "V", time: "5 min", difficulty: "Easy", status: "locked" },
  { id: 194, code: "I67", stage: "six", title: "Communication Reflection with Mentor", category: "V", time: "30 min", difficulty: "Moderate", status: "locked" },
  { id: 195, code: "I70", stage: "six", title: "Reflection on Persuasion Techniques", category: "V", time: "20 to 30 min", difficulty: "Easy", status: "locked" },
  { id: 196, code: "I34", stage: "six", title: "Documented Communication Goals", category: "W", time: "20 min", difficulty: "Easy", status: "locked" },
  { id: 197, code: "I43", stage: "six", title: "Visual Communication Exercise", category: "W", time: "30 to 45 min", difficulty: "Moderate", status: "locked" },
  { id: 198, code: "I52", stage: "six", title: "Active Note-Taking System", category: "W", time: "15 min setup", difficulty: "Easy", status: "locked" },
  { id: 199, code: "I56", stage: "six", title: "Communication Flow Mapping", category: "W", time: "30 min", difficulty: "Moderate", status: "locked" },
  { id: 200, code: "I58", stage: "six", title: "Storyboard Creation", category: "W", time: "20 to 30 min", difficulty: "Easy", status: "locked" },
  { id: 201, code: "I59", stage: "six", title: "Communication Metrics Tracking", category: "W", time: "10 min/wk", difficulty: "Easy", status: "locked" },
  { id: 202, code: "I61", stage: "six", title: "Interview Question Bank Created", category: "W", time: "2 to 3 hrs", difficulty: "Moderate", status: "locked" },
  { id: 203, code: "I68", stage: "six", title: "Communication Challenge Goal", category: "W", time: "10 min/wk", difficulty: "Easy", status: "locked" },
];

export const FIRSTS: FirstModule[] = [...STAGE_ONE_FIRSTS, ...STAGE_TWO_FIRSTS, ...STAGE_THREE_FIRSTS, ...STAGE_FOUR_FIRSTS, ...STAGE_FIVE_FIRSTS, ...STAGE_SIX_FIRSTS];

export const MOCK_USER = {
  firstName: "Ada",
  role: "Independent · Early professional",
  streakDays: 5,
  stage: "Stage One · Self-Awareness & Career Clarity",
};

export function completionStats(modules: FirstModule[]) {
  const complete = modules.filter((m) => m.status === "complete").length;
  return { complete, total: modules.length, pct: Math.round((complete / modules.length) * 100) };
}
